
package Interface;

import Controlador.Controlador;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author karol
 */
public class UIHome extends javax.swing.JFrame {
    
    /**
     * Creates new form UIHome
     */
    public UIHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuDep = new javax.swing.JMenu();
        MenuAddDep = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuAddEfetivo = new javax.swing.JMenuItem();
        MenuAddTecnico = new javax.swing.JMenuItem();
        MenuAddSub = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuRelatDep = new javax.swing.JMenuItem();
        MenuRelatTec = new javax.swing.JMenu();
        MenuRelatFunGeral = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuRelatDocGeral = new javax.swing.JMenuItem();
        MenuRelatEfetivo = new javax.swing.JMenuItem();
        MenuRelatSub = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        MenuBuscarFunFaixa = new javax.swing.JMenuItem();
        MenuBuscarFunNome = new javax.swing.JMenuItem();
        MenuBuscarFunCod = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MenuBuscarDepFaixa = new javax.swing.JMenuItem();
        MenuBuscarDepNome = new javax.swing.JMenuItem();
        MenuBuscarDepCod = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/images/imageBackground.jpeg"))); // NOI18N

        MenuDep.setText("Cadastrar Departamento");
        MenuDep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDepActionPerformed(evt);
            }
        });

        MenuAddDep.setText("Cadastrar em UNESP");
        MenuAddDep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuAddDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddDepActionPerformed(evt);
            }
        });
        MenuDep.add(MenuAddDep);

        jMenuBar1.add(MenuDep);

        jMenu2.setText("Cadastrar Funcionário");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuAddEfetivo.setText("Efetivo");
        MenuAddEfetivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuAddEfetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddEfetivoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAddEfetivo);

        MenuAddTecnico.setText("Técnico");
        MenuAddTecnico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuAddTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddTecnicoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAddTecnico);

        MenuAddSub.setText("Substituto");
        MenuAddSub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuAddSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddSubActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAddSub);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MenuRelatDep.setText("Departamentos");
        MenuRelatDep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuRelatDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatDepActionPerformed(evt);
            }
        });
        jMenu3.add(MenuRelatDep);

        MenuRelatTec.setText("Funcionários");
        MenuRelatTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatTecActionPerformed(evt);
            }
        });

        MenuRelatFunGeral.setText("Geral");
        MenuRelatFunGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatFunGeralActionPerformed(evt);
            }
        });
        MenuRelatTec.add(MenuRelatFunGeral);

        jMenuItem1.setText("Tecnico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuRelatTec.add(jMenuItem1);

        jMenu5.setText("Docentes");

        MenuRelatDocGeral.setText("Geral");
        MenuRelatDocGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatDocGeralActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRelatDocGeral);

        MenuRelatEfetivo.setText("Efetivos");
        MenuRelatEfetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatEfetivoActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRelatEfetivo);

        MenuRelatSub.setText("Substitutos");
        MenuRelatSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatSubActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRelatSub);

        MenuRelatTec.add(jMenu5);

        jMenu3.add(MenuRelatTec);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Buscar");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu6.setText("Funcionarios");

        MenuBuscarFunFaixa.setText("Faixa Salarial");
        MenuBuscarFunFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarFunFaixaActionPerformed(evt);
            }
        });
        jMenu6.add(MenuBuscarFunFaixa);

        MenuBuscarFunNome.setText("Nome");
        MenuBuscarFunNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarFunNomeActionPerformed(evt);
            }
        });
        jMenu6.add(MenuBuscarFunNome);

        MenuBuscarFunCod.setText("Código");
        MenuBuscarFunCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarFunCodActionPerformed(evt);
            }
        });
        jMenu6.add(MenuBuscarFunCod);

        jMenu4.add(jMenu6);

        jMenu7.setText("Departamento");

        MenuBuscarDepFaixa.setText("Faixa Salarial");
        MenuBuscarDepFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarDepFaixaActionPerformed(evt);
            }
        });
        jMenu7.add(MenuBuscarDepFaixa);

        MenuBuscarDepNome.setText("Nome");
        MenuBuscarDepNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarDepNomeActionPerformed(evt);
            }
        });
        jMenu7.add(MenuBuscarDepNome);

        MenuBuscarDepCod.setText("Código");
        MenuBuscarDepCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarDepCodActionPerformed(evt);
            }
        });
        jMenu7.add(MenuBuscarDepCod);

        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDepActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_MenuDepActionPerformed

    private void MenuRelatDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatDepActionPerformed
        // TODO add your handling code here:
        UIRelatorio relatorio = new UIRelatorio(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Departamentos", "Relatório Departamentos ", control.dadosTodosDepartamentos());
        
    }//GEN-LAST:event_MenuRelatDepActionPerformed

    private void MenuAddEfetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddEfetivoActionPerformed
        UICadastroEfetivo CadastroEfetivo = new UICadastroEfetivo(this, true);
        CadastroEfetivo.setLocationRelativeTo(null);
        CadastroEfetivo.setVisible(true);
    }//GEN-LAST:event_MenuAddEfetivoActionPerformed

    private void MenuAddDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddDepActionPerformed
        // TODO add your handling code here:
        UICadastroDep CadastroDep = new UICadastroDep(this, true);
        CadastroDep.setLocationRelativeTo(null);
        CadastroDep.setVisible(true);
    }//GEN-LAST:event_MenuAddDepActionPerformed

    private void MenuAddTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddTecnicoActionPerformed
        // TODO add your handling code here:
        UICadastroTecnico CadastroTec = new UICadastroTecnico(this, true);
        CadastroTec.setLocationRelativeTo(null);
        CadastroTec.setVisible(true);
    }//GEN-LAST:event_MenuAddTecnicoActionPerformed

    private void MenuAddSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddSubActionPerformed
        // TODO add your handling code here:
        UICadastroSub CadastroSub = new UICadastroSub(this, true);
        CadastroSub.setLocationRelativeTo(null);
        CadastroSub.setVisible(true);
    }//GEN-LAST:event_MenuAddSubActionPerformed

    private void MenuRelatFunGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatFunGeralActionPerformed
        // TODO add your handling code here:
        UIRelatorio relatorio = new UIRelatorio(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Funcionários", "Relatório Funcionários ", control.dadosTodosFuncionarios());
    }//GEN-LAST:event_MenuRelatFunGeralActionPerformed

    private void MenuRelatTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatTecActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_MenuRelatTecActionPerformed

    private void MenuBuscarDepNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarDepNomeActionPerformed
        // TODO add your handling code here:
        UIBuscaDeptoNome buscaDeptoNome = new UIBuscaDeptoNome(this, false);
        buscaDeptoNome.setVisible(true);
    }//GEN-LAST:event_MenuBuscarDepNomeActionPerformed

    private void MenuBuscarDepFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarDepFaixaActionPerformed
        // TODO add your handling code here:
        UIBuscaDeptoFaixaSalarial buscaFaixaSalarial = new UIBuscaDeptoFaixaSalarial(this,false );
        buscaFaixaSalarial.setVisible(true);
    }//GEN-LAST:event_MenuBuscarDepFaixaActionPerformed

    private void MenuBuscarDepCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarDepCodActionPerformed
        // TODO add your handling code here:
        UIBuscaDepto buscadepto = new UIBuscaDepto(this,false);
        buscadepto.setVisible(true);
    }//GEN-LAST:event_MenuBuscarDepCodActionPerformed

    private void MenuBuscarFunCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarFunCodActionPerformed
        // TODO add your handling code here:
        UIBuscaFuncCodigo buscaFuncionarioCodigo = new UIBuscaFuncCodigo(this,false);
        buscaFuncionarioCodigo.setVisible(true);
    }//GEN-LAST:event_MenuBuscarFunCodActionPerformed

    private void MenuBuscarFunNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarFunNomeActionPerformed
        // TODO add your handling code here:
        UIBuscaFuncNome buscaFuncionarioNome = new UIBuscaFuncNome(this,false);
        buscaFuncionarioNome.setVisible(true);
    }//GEN-LAST:event_MenuBuscarFunNomeActionPerformed

    private void MenuBuscarFunFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarFunFaixaActionPerformed
        // TODO add your handling code here:
        UIBuscaFuncFaixaSalarial buscaFucionarioFaixaSalarial = new UIBuscaFuncFaixaSalarial(this,false);
        buscaFucionarioFaixaSalarial.setVisible(true);
    }//GEN-LAST:event_MenuBuscarFunFaixaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        UIRelatorio relatorio = new UIRelatorio(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Tecnico","Relatório Técnico",control.exibirTecnicos());  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuRelatDocGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatDocGeralActionPerformed
        // TODO add your handling code here:
        UIRelatorio relatorio = new UIRelatorio(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Docentes","Relatório Docentes",control.exibirDocentes());  
    }//GEN-LAST:event_MenuRelatDocGeralActionPerformed

    private void MenuRelatEfetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatEfetivoActionPerformed
        // TODO add your handling code here:
        UIRelatorio relatorio = new UIRelatorio(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Efetivos","Relatório Efetivos",control.exibirEfetivos());  
    }//GEN-LAST:event_MenuRelatEfetivoActionPerformed

    private void MenuRelatSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatSubActionPerformed
        // TODO add your handling code here:
        UIRelatorio relatorio = new UIRelatorio(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Substituto","Relatório Substituto",control.exibirSubstituto());  
    }//GEN-LAST:event_MenuRelatSubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAddDep;
    private javax.swing.JMenuItem MenuAddEfetivo;
    private javax.swing.JMenuItem MenuAddSub;
    private javax.swing.JMenuItem MenuAddTecnico;
    private javax.swing.JMenuItem MenuBuscarDepCod;
    private javax.swing.JMenuItem MenuBuscarDepFaixa;
    private javax.swing.JMenuItem MenuBuscarDepNome;
    private javax.swing.JMenuItem MenuBuscarFunCod;
    private javax.swing.JMenuItem MenuBuscarFunFaixa;
    private javax.swing.JMenuItem MenuBuscarFunNome;
    private javax.swing.JMenu MenuDep;
    private javax.swing.JMenuItem MenuRelatDep;
    private javax.swing.JMenuItem MenuRelatDocGeral;
    private javax.swing.JMenuItem MenuRelatEfetivo;
    private javax.swing.JMenuItem MenuRelatFunGeral;
    private javax.swing.JMenuItem MenuRelatSub;
    private javax.swing.JMenu MenuRelatTec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
